# Configure PAM file sshd for redhat 7 and 8

- name: Configure line "auth  required pam_sepermit.so" at sshd at the begining
  pam_handler:
    service_name: sshd
    backup: true
    log: true
    first: true
    module_type: auth
    control_flags: required
    module_path: pam_sepermit.so
    module_options: ""
    state: present

- name: Configure line "auth  substack password-auth" at sshd after previous line
  pam_handler:
    service_name: sshd
    log: true

    reference_module_type: auth
    reference_control_flags: required
    reference_module_path: pam_sepermit.so

    module_type: auth
    control_flags: substack
    module_path: password-auth
    module_options: ""
    
    state: presentafter

- name: Configure line "auth  required pam_env.so" at sshd after previous line
  pam_handler:
    service_name: sshd
    log: true

    reference_module_type: auth
    reference_control_flags: substack
    reference_module_path: password-auth

    module_type: auth
    control_flags: required
    module_path: pam_env.so
    module_options: ""
    
    state: presentafter

#
- name: Comment line "auth  substack password-auth" 
  pam_handler:
    service_name: sshd
    log: true

    module_type: auth
    control_flags: substack
    module_path: password-auth
    
    state: comment
#

- name: Configure line "auth  sufficient pam_duo.so" at sshd after previous line
  pam_handler:
    service_name: sshd
    log: true

    reference_module_type: auth
    reference_control_flags: required
    reference_module_path: pam_env.so

    module_type: auth
    control_flags: sufficient
    module_path: pam_duo.so
    module_options: ""
    
    state: presentafter

- name: Configure line "auth requisite pam_succeed_if.so uid >= 1000 quiet_success" at sshd after previous line
  pam_handler:
    service_name: sshd
    log: true

    reference_module_type: auth
    reference_control_flags: sufficient
    reference_module_path: pam_duo.so

    module_type: auth
    control_flags: requisite
    module_path: pam_succeed_if.so
    module_options: ""
    
    state: presentafter

- name: Configure line "auth  required pam_deny.so" at sshd after previous line
  pam_handler:
    service_name: sshd
    log: true

    reference_module_type: auth
    reference_control_flags: requisite
    reference_module_path: pam_succeed_if.so

    module_type: auth
    control_flags: required
    module_path: pam_deny.so
    module_options: ""
    
    state: presentafter


- name: Configure line "auth  include postlogin" at sshd after previous line
  pam_handler:
    service_name: sshd
    log: true

    reference_module_type: auth
    reference_control_flags: required
    reference_module_path: pam_deny.so

    module_type: auth
    control_flags: include
    module_path: postlogin
    module_options: ""
    
    state: presentafter
    